// Code generated by protoc-gen-go. DO NOT EDIT.
// source: training.proto

package training

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrainingType int32

const (
	TrainingType_UNDEFINED   TrainingType = 0
	TrainingType_FOR_TIME    TrainingType = 1
	TrainingType_AMRAP       TrainingType = 2
	TrainingType_EMOM        TrainingType = 3
	TrainingType_TABATA      TrainingType = 4
	TrainingType_FOR_QUALITY TrainingType = 5
	TrainingType_AFRAP       TrainingType = 6
)

var TrainingType_name = map[int32]string{
	0: "UNDEFINED",
	1: "FOR_TIME",
	2: "AMRAP",
	3: "EMOM",
	4: "TABATA",
	5: "FOR_QUALITY",
	6: "AFRAP",
}

var TrainingType_value = map[string]int32{
	"UNDEFINED":   0,
	"FOR_TIME":    1,
	"AMRAP":       2,
	"EMOM":        3,
	"TABATA":      4,
	"FOR_QUALITY": 5,
	"AFRAP":       6,
}

func (x TrainingType) String() string {
	return proto.EnumName(TrainingType_name, int32(x))
}

func (TrainingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e5eb1bf9ae033d5, []int{0}
}

type Training struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date                 string       `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Type                 TrainingType `protobuf:"varint,3,opt,name=type,proto3,enum=training.TrainingType" json:"type,omitempty"`
	TimeCap              int32        `protobuf:"varint,4,opt,name=time_cap,json=timeCap,proto3" json:"time_cap,omitempty"`
	Score                string       `protobuf:"bytes,5,opt,name=score,proto3" json:"score,omitempty"`
	Notes                string       `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Training) Reset()         { *m = Training{} }
func (m *Training) String() string { return proto.CompactTextString(m) }
func (*Training) ProtoMessage()    {}
func (*Training) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e5eb1bf9ae033d5, []int{0}
}

func (m *Training) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Training.Unmarshal(m, b)
}
func (m *Training) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Training.Marshal(b, m, deterministic)
}
func (m *Training) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Training.Merge(m, src)
}
func (m *Training) XXX_Size() int {
	return xxx_messageInfo_Training.Size(m)
}
func (m *Training) XXX_DiscardUnknown() {
	xxx_messageInfo_Training.DiscardUnknown(m)
}

var xxx_messageInfo_Training proto.InternalMessageInfo

func (m *Training) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Training) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Training) GetType() TrainingType {
	if m != nil {
		return m.Type
	}
	return TrainingType_UNDEFINED
}

func (m *Training) GetTimeCap() int32 {
	if m != nil {
		return m.TimeCap
	}
	return 0
}

func (m *Training) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *Training) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type DeleteTrainingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTrainingRequest) Reset()         { *m = DeleteTrainingRequest{} }
func (m *DeleteTrainingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTrainingRequest) ProtoMessage()    {}
func (*DeleteTrainingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e5eb1bf9ae033d5, []int{1}
}

func (m *DeleteTrainingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTrainingRequest.Unmarshal(m, b)
}
func (m *DeleteTrainingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTrainingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTrainingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTrainingRequest.Merge(m, src)
}
func (m *DeleteTrainingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTrainingRequest.Size(m)
}
func (m *DeleteTrainingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTrainingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTrainingRequest proto.InternalMessageInfo

func (m *DeleteTrainingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("training.TrainingType", TrainingType_name, TrainingType_value)
	proto.RegisterType((*Training)(nil), "training.Training")
	proto.RegisterType((*DeleteTrainingRequest)(nil), "training.DeleteTrainingRequest")
}

func init() { proto.RegisterFile("training.proto", fileDescriptor_1e5eb1bf9ae033d5) }

var fileDescriptor_1e5eb1bf9ae033d5 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x5d, 0x68, 0x6b, 0x19, 0x11, 0x37, 0x13, 0x31, 0xeb, 0x8d, 0x70, 0x22, 0x98, 0x70,
	0xd0, 0x5f, 0xb0, 0x48, 0x49, 0x48, 0x2c, 0xe8, 0x66, 0x39, 0xe8, 0x85, 0x54, 0x9c, 0x28, 0x89,
	0xb4, 0xb5, 0x5d, 0x0f, 0xfc, 0x20, 0x2f, 0xfe, 0x4a, 0xb3, 0x5b, 0xdb, 0x78, 0xf0, 0xf6, 0xbe,
	0x97, 0x99, 0x37, 0x93, 0x07, 0x3d, 0x53, 0x24, 0xbb, 0x74, 0x97, 0xbe, 0x4e, 0xf2, 0x22, 0x33,
	0x19, 0x86, 0x35, 0x0f, 0xbf, 0x18, 0x84, 0xfa, 0x17, 0x10, 0xc1, 0x4b, 0x93, 0x3d, 0x09, 0x36,
	0x60, 0xa3, 0x8e, 0x72, 0xda, 0x7a, 0x2f, 0x89, 0x21, 0xd1, 0xaa, 0x3c, 0xab, 0x71, 0x0c, 0x9e,
	0x39, 0xe4, 0x24, 0xda, 0x03, 0x36, 0xea, 0x5d, 0x5f, 0x4c, 0x9a, 0xf4, 0x3a, 0x49, 0x1f, 0x72,
	0x52, 0x6e, 0x06, 0x2f, 0x21, 0x34, 0xbb, 0x3d, 0x6d, 0xb6, 0x49, 0x2e, 0xbc, 0x01, 0x1b, 0xf9,
	0xea, 0xd8, 0xf2, 0x6d, 0x92, 0xe3, 0x39, 0xf8, 0xe5, 0x36, 0x2b, 0x48, 0xf8, 0x2e, 0xbb, 0x02,
	0xeb, 0xa6, 0x99, 0xa1, 0x52, 0x04, 0x95, 0xeb, 0x60, 0x78, 0x05, 0xfd, 0x19, 0xbd, 0x93, 0xa1,
	0xfa, 0x84, 0xa2, 0x8f, 0x4f, 0x2a, 0xcd, 0x7f, 0x3f, 0x8f, 0xdf, 0xa0, 0xfb, 0xf7, 0x13, 0x3c,
	0x85, 0xce, 0x7a, 0x39, 0x8b, 0xe6, 0x8b, 0x65, 0x34, 0xe3, 0x47, 0xd8, 0x85, 0x70, 0xbe, 0x52,
	0x1b, 0xbd, 0x88, 0x23, 0xce, 0xb0, 0x03, 0xbe, 0x8c, 0x95, 0xbc, 0xe7, 0x2d, 0x0c, 0xc1, 0x8b,
	0xe2, 0x55, 0xcc, 0xdb, 0x08, 0x10, 0x68, 0x39, 0x95, 0x5a, 0x72, 0x0f, 0xcf, 0xe0, 0xc4, 0x8e,
	0x3f, 0xac, 0xe5, 0xdd, 0x42, 0x3f, 0x72, 0xdf, 0x6d, 0xcc, 0xed, 0x46, 0x30, 0xed, 0x3f, 0x35,
	0x55, 0x7e, 0xb7, 0x1a, 0xf9, 0x1c, 0xb8, 0x9a, 0x6f, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xab,
	0xe8, 0x35, 0x0e, 0x78, 0x01, 0x00, 0x00,
}
