// Code generated by protoc-gen-go. DO NOT EDIT.
// source: training.proto

package training

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MovementType int32

const (
	MovementType_WEIGHTLIFTING MovementType = 0
	MovementType_GYM           MovementType = 1
	MovementType_CARDIO        MovementType = 2
)

var MovementType_name = map[int32]string{
	0: "WEIGHTLIFTING",
	1: "GYM",
	2: "CARDIO",
}

var MovementType_value = map[string]int32{
	"WEIGHTLIFTING": 0,
	"GYM":           1,
	"CARDIO":        2,
}

func (x MovementType) String() string {
	return proto.EnumName(MovementType_name, int32(x))
}

func (MovementType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e5eb1bf9ae033d5, []int{0}
}

type TrainingType int32

const (
	TrainingType_FOR_TIME    TrainingType = 0
	TrainingType_AMRAP       TrainingType = 1
	TrainingType_EMOM        TrainingType = 2
	TrainingType_TABATA      TrainingType = 3
	TrainingType_FOR_QUALITY TrainingType = 4
	TrainingType_AFSAP       TrainingType = 5
)

var TrainingType_name = map[int32]string{
	0: "FOR_TIME",
	1: "AMRAP",
	2: "EMOM",
	3: "TABATA",
	4: "FOR_QUALITY",
	5: "AFSAP",
}

var TrainingType_value = map[string]int32{
	"FOR_TIME":    0,
	"AMRAP":       1,
	"EMOM":        2,
	"TABATA":      3,
	"FOR_QUALITY": 4,
	"AFSAP":       5,
}

func (x TrainingType) String() string {
	return proto.EnumName(TrainingType_name, int32(x))
}

func (TrainingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e5eb1bf9ae033d5, []int{1}
}

type Exercise struct {
	Movement             MovementType `protobuf:"varint,1,opt,name=movement,proto3,enum=training.MovementType" json:"movement,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Exercise) Reset()         { *m = Exercise{} }
func (m *Exercise) String() string { return proto.CompactTextString(m) }
func (*Exercise) ProtoMessage()    {}
func (*Exercise) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e5eb1bf9ae033d5, []int{0}
}

func (m *Exercise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exercise.Unmarshal(m, b)
}
func (m *Exercise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exercise.Marshal(b, m, deterministic)
}
func (m *Exercise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exercise.Merge(m, src)
}
func (m *Exercise) XXX_Size() int {
	return xxx_messageInfo_Exercise.Size(m)
}
func (m *Exercise) XXX_DiscardUnknown() {
	xxx_messageInfo_Exercise.DiscardUnknown(m)
}

var xxx_messageInfo_Exercise proto.InternalMessageInfo

func (m *Exercise) GetMovement() MovementType {
	if m != nil {
		return m.Movement
	}
	return MovementType_WEIGHTLIFTING
}

func (m *Exercise) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Training struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 TrainingType `protobuf:"varint,2,opt,name=type,proto3,enum=training.TrainingType" json:"type,omitempty"`
	Exercises            []*Exercise  `protobuf:"bytes,3,rep,name=exercises,proto3" json:"exercises,omitempty"`
	TimeCap              int32        `protobuf:"varint,4,opt,name=time_cap,json=timeCap,proto3" json:"time_cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Training) Reset()         { *m = Training{} }
func (m *Training) String() string { return proto.CompactTextString(m) }
func (*Training) ProtoMessage()    {}
func (*Training) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e5eb1bf9ae033d5, []int{1}
}

func (m *Training) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Training.Unmarshal(m, b)
}
func (m *Training) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Training.Marshal(b, m, deterministic)
}
func (m *Training) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Training.Merge(m, src)
}
func (m *Training) XXX_Size() int {
	return xxx_messageInfo_Training.Size(m)
}
func (m *Training) XXX_DiscardUnknown() {
	xxx_messageInfo_Training.DiscardUnknown(m)
}

var xxx_messageInfo_Training proto.InternalMessageInfo

func (m *Training) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Training) GetType() TrainingType {
	if m != nil {
		return m.Type
	}
	return TrainingType_FOR_TIME
}

func (m *Training) GetExercises() []*Exercise {
	if m != nil {
		return m.Exercises
	}
	return nil
}

func (m *Training) GetTimeCap() int32 {
	if m != nil {
		return m.TimeCap
	}
	return 0
}

func init() {
	proto.RegisterEnum("training.MovementType", MovementType_name, MovementType_value)
	proto.RegisterEnum("training.TrainingType", TrainingType_name, TrainingType_value)
	proto.RegisterType((*Exercise)(nil), "training.Exercise")
	proto.RegisterType((*Training)(nil), "training.Training")
}

func init() { proto.RegisterFile("training.proto", fileDescriptor_1e5eb1bf9ae033d5) }

var fileDescriptor_1e5eb1bf9ae033d5 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xd9, 0xb6, 0xc0, 0x32, 0x20, 0xae, 0x93, 0x68, 0xea, 0xad, 0xe1, 0xd4, 0x70, 0x20,
	0x06, 0x13, 0xef, 0x0b, 0x16, 0xdc, 0x84, 0x15, 0x5c, 0xd7, 0x18, 0xbc, 0x90, 0x4a, 0x36, 0xa6,
	0x87, 0x96, 0x06, 0x1a, 0x23, 0x4f, 0xe2, 0x3b, 0xf8, 0x94, 0x86, 0x4a, 0x5b, 0xbc, 0xcd, 0x64,
	0xbf, 0x2f, 0xf3, 0x6f, 0x7e, 0xe8, 0x66, 0xdb, 0x30, 0x4a, 0xa2, 0xe4, 0x63, 0x90, 0x6e, 0x37,
	0xd9, 0x06, 0x69, 0xb1, 0xf7, 0x14, 0xd0, 0xe0, 0xcb, 0x6c, 0xd7, 0xd1, 0xce, 0xe0, 0x10, 0x68,
	0xbc, 0xf9, 0x34, 0xb1, 0x49, 0x32, 0x97, 0x78, 0xc4, 0xef, 0x0e, 0xaf, 0x06, 0xa5, 0x28, 0x8f,
	0x2f, 0x7a, 0x9f, 0x1a, 0x55, 0x72, 0x88, 0xe0, 0x24, 0x61, 0x6c, 0x5c, 0xcb, 0x23, 0x7e, 0x4b,
	0xe5, 0x73, 0xef, 0x9b, 0x00, 0xd5, 0x47, 0xaf, 0x04, 0x48, 0x05, 0x60, 0x1f, 0x9c, 0x6c, 0x9f,
	0xfe, 0x49, 0xff, 0x8e, 0x14, 0x56, 0x7e, 0x24, 0x67, 0xf0, 0x06, 0x5a, 0xe6, 0x18, 0x70, 0xe7,
	0xda, 0x9e, 0xed, 0xb7, 0x87, 0x58, 0x09, 0x45, 0x76, 0x55, 0x41, 0x78, 0x0d, 0x34, 0x8b, 0x62,
	0xb3, 0x5a, 0x87, 0xa9, 0xeb, 0x78, 0xc4, 0xaf, 0xab, 0xe6, 0x61, 0x1f, 0x87, 0x69, 0xff, 0x0e,
	0x3a, 0xa7, 0xff, 0xc0, 0x0b, 0x38, 0x7b, 0x0d, 0xc4, 0xf4, 0x41, 0xcf, 0xc4, 0x44, 0x8b, 0xc7,
	0x29, 0xab, 0x61, 0x13, 0xec, 0xe9, 0x52, 0x32, 0x82, 0x00, 0x8d, 0x31, 0x57, 0xf7, 0x62, 0xce,
	0xac, 0xfe, 0x12, 0x3a, 0xa7, 0xd1, 0xb0, 0x03, 0x74, 0x32, 0x57, 0x2b, 0x2d, 0x64, 0xc0, 0x6a,
	0xd8, 0x82, 0x3a, 0x97, 0x8a, 0x2f, 0x18, 0x41, 0x0a, 0x4e, 0x20, 0xe7, 0x92, 0x59, 0x07, 0x5d,
	0xf3, 0x11, 0xd7, 0x9c, 0xd9, 0x78, 0x0e, 0xed, 0x03, 0xfe, 0xf4, 0xc2, 0x67, 0x42, 0x2f, 0x99,
	0x93, 0x1b, 0x93, 0x67, 0xbe, 0x60, 0xf5, 0xd1, 0xe5, 0x5b, 0x59, 0xc6, 0x8f, 0x55, 0x8e, 0xef,
	0x8d, 0xbc, 0xa8, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x56, 0xe9, 0x77, 0xba, 0x01,
	0x00, 0x00,
}
