// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Birthday             string   `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	PictureUrl           string   `protobuf:"bytes,6,opt,name=picture_url,json=pictureUrl,proto3" json:"picture_url,omitempty"`
	Height               float64  `protobuf:"fixed64,7,opt,name=height,proto3" json:"height,omitempty"`
	Weight               float64  `protobuf:"fixed64,8,opt,name=weight,proto3" json:"weight,omitempty"`
	AffiliatedBox        string   `protobuf:"bytes,9,opt,name=affiliated_box,json=affiliatedBox,proto3" json:"affiliated_box,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetPictureUrl() string {
	if m != nil {
		return m.PictureUrl
	}
	return ""
}

func (m *User) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *User) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *User) GetAffiliatedBox() string {
	if m != nil {
		return m.AffiliatedBox
	}
	return ""
}

type Login struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Signup struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Firstname            string   `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Birthday             string   `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	PictureUrl           string   `protobuf:"bytes,7,opt,name=picture_url,json=pictureUrl,proto3" json:"picture_url,omitempty"`
	Height               float32  `protobuf:"fixed32,8,opt,name=height,proto3" json:"height,omitempty"`
	Weight               float32  `protobuf:"fixed32,9,opt,name=weight,proto3" json:"weight,omitempty"`
	AffiliatedBox        string   `protobuf:"bytes,10,opt,name=affiliated_box,json=affiliatedBox,proto3" json:"affiliated_box,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signup) Reset()         { *m = Signup{} }
func (m *Signup) String() string { return proto.CompactTextString(m) }
func (*Signup) ProtoMessage()    {}
func (*Signup) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Signup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signup.Unmarshal(m, b)
}
func (m *Signup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signup.Marshal(b, m, deterministic)
}
func (m *Signup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signup.Merge(m, src)
}
func (m *Signup) XXX_Size() int {
	return xxx_messageInfo_Signup.Size(m)
}
func (m *Signup) XXX_DiscardUnknown() {
	xxx_messageInfo_Signup.DiscardUnknown(m)
}

var xxx_messageInfo_Signup proto.InternalMessageInfo

func (m *Signup) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Signup) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Signup) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Signup) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Signup) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Signup) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Signup) GetPictureUrl() string {
	if m != nil {
		return m.PictureUrl
	}
	return ""
}

func (m *Signup) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Signup) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Signup) GetAffiliatedBox() string {
	if m != nil {
		return m.AffiliatedBox
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Login)(nil), "user.Login")
	proto.RegisterType((*Signup)(nil), "user.Signup")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6b, 0x83, 0x30,
	0x14, 0xc7, 0xd1, 0xaa, 0xd5, 0x37, 0xba, 0x43, 0x18, 0x23, 0x94, 0xc1, 0x8a, 0x30, 0xe8, 0x69,
	0x97, 0x9d, 0x76, 0xed, 0x79, 0xa7, 0x8e, 0x5e, 0x76, 0x29, 0x71, 0x46, 0x0d, 0xa4, 0x46, 0x92,
	0x48, 0xbb, 0xef, 0xb3, 0xd3, 0x3e, 0xda, 0x3e, 0xc5, 0x48, 0xe2, 0x6c, 0x85, 0xea, 0x49, 0xff,
	0xbf, 0x3f, 0x79, 0xf0, 0x7e, 0x3c, 0x80, 0x56, 0x51, 0xf9, 0xdc, 0x48, 0xa1, 0x05, 0x0a, 0xcc,
	0x7f, 0xfa, 0xeb, 0x41, 0xb0, 0x53, 0x54, 0xa2, 0x3b, 0x08, 0xe9, 0x81, 0x30, 0x8e, 0xbd, 0x95,
	0xb7, 0x4e, 0xb6, 0x2e, 0xa0, 0x07, 0x48, 0x0a, 0x26, 0x95, 0xae, 0xc9, 0x81, 0x62, 0xdf, 0x36,
	0x67, 0x80, 0x96, 0x10, 0x73, 0xd2, 0x95, 0x33, 0x5b, 0xf6, 0xd9, 0x74, 0x19, 0x93, 0xba, 0xca,
	0xc9, 0x17, 0x0e, 0x5c, 0xf7, 0x9f, 0xd1, 0x23, 0xdc, 0x34, 0xec, 0x53, 0xb7, 0x92, 0xee, 0x5b,
	0xc9, 0x71, 0x64, 0x6b, 0xe8, 0xd0, 0x4e, 0x72, 0x74, 0x0f, 0x51, 0x45, 0x59, 0x59, 0x69, 0x3c,
	0x5f, 0x79, 0x6b, 0x6f, 0xdb, 0x25, 0xc3, 0x8f, 0x8e, 0xc7, 0x8e, 0xbb, 0x84, 0x9e, 0xe0, 0x96,
	0x14, 0x05, 0xe3, 0x8c, 0x68, 0x9a, 0xef, 0x33, 0x71, 0xc2, 0x89, 0x9d, 0xb9, 0x38, 0xd3, 0x8d,
	0x38, 0xa5, 0xaf, 0x10, 0xbe, 0x89, 0x92, 0xd5, 0x23, 0xcb, 0x2e, 0x21, 0x6e, 0x88, 0x52, 0x47,
	0x21, 0xf3, 0x6e, 0xd7, 0x3e, 0xa7, 0xdf, 0x3e, 0x44, 0xef, 0xac, 0xac, 0xdb, 0x66, 0xfc, 0xb1,
	0x11, 0x7a, 0x21, 0xaa, 0xcf, 0x83, 0xc1, 0xb3, 0xe1, 0xe0, 0xa1, 0xe1, 0x60, 0xca, 0x70, 0x38,
	0x61, 0x38, 0x9a, 0x36, 0x3c, 0x9f, 0x30, 0x6c, 0x4c, 0xfa, 0x57, 0x0c, 0x27, 0x8e, 0x8f, 0x1a,
	0x86, 0x2b, 0x86, 0x37, 0x8b, 0x0f, 0x7b, 0x56, 0x3f, 0xbe, 0xfd, 0x64, 0x91, 0x3d, 0xb5, 0x97,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xa4, 0xad, 0x83, 0x78, 0x02, 0x00, 0x00,
}
