// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movement_record.proto

package movement_record

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MovementRecord struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Weight               float64              `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MovementRecord) Reset()         { *m = MovementRecord{} }
func (m *MovementRecord) String() string { return proto.CompactTextString(m) }
func (*MovementRecord) ProtoMessage()    {}
func (*MovementRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b27cdd15286da9, []int{0}
}

func (m *MovementRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovementRecord.Unmarshal(m, b)
}
func (m *MovementRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovementRecord.Marshal(b, m, deterministic)
}
func (m *MovementRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovementRecord.Merge(m, src)
}
func (m *MovementRecord) XXX_Size() int {
	return xxx_messageInfo_MovementRecord.Size(m)
}
func (m *MovementRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MovementRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MovementRecord proto.InternalMessageInfo

func (m *MovementRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MovementRecord) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *MovementRecord) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type DeleteMovementRecordRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovementRecordRequest) Reset()         { *m = DeleteMovementRecordRequest{} }
func (m *DeleteMovementRecordRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovementRecordRequest) ProtoMessage()    {}
func (*DeleteMovementRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b27cdd15286da9, []int{1}
}

func (m *DeleteMovementRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovementRecordRequest.Unmarshal(m, b)
}
func (m *DeleteMovementRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovementRecordRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovementRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovementRecordRequest.Merge(m, src)
}
func (m *DeleteMovementRecordRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovementRecordRequest.Size(m)
}
func (m *DeleteMovementRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovementRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovementRecordRequest proto.InternalMessageInfo

func (m *DeleteMovementRecordRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*MovementRecord)(nil), "movement_record.MovementRecord")
	proto.RegisterType((*DeleteMovementRecordRequest)(nil), "movement_record.DeleteMovementRecordRequest")
}

func init() { proto.RegisterFile("movement_record.proto", fileDescriptor_b5b27cdd15286da9) }

var fileDescriptor_b5b27cdd15286da9 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0xcd, 0x2f, 0x4b,
	0xcd, 0x4d, 0xcd, 0x2b, 0x89, 0x2f, 0x4a, 0x4d, 0xce, 0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x47, 0x13, 0x96, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x4b,
	0x27, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x74, 0x28,
	0xe5, 0x70, 0xf1, 0xf9, 0x42, 0xf5, 0x04, 0x81, 0xb5, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6,
	0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x7a, 0x5c, 0x2c, 0x29, 0x89,
	0x25, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x52, 0x7a, 0x10, 0x53, 0xf5, 0x60, 0xa6,
	0xea, 0x85, 0xc0, 0x4c, 0x0d, 0x02, 0xab, 0x13, 0x12, 0xe3, 0x62, 0x2b, 0x4f, 0xcd, 0x4c, 0xcf,
	0x28, 0x91, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0c, 0x82, 0xf2, 0x94, 0x0c, 0xb9, 0xa4, 0x5d, 0x52,
	0x73, 0x52, 0x4b, 0x52, 0x51, 0xed, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xc1, 0x66, 0xb5,
	0x93, 0x72, 0x14, 0xba, 0xa7, 0x56, 0x31, 0xa1, 0x8b, 0x24, 0xb1, 0x81, 0x5d, 0x62, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xa0, 0xd5, 0x1f, 0x79, 0x17, 0x01, 0x00, 0x00,
}
